<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Dheekshu" failures="1" tests="3" name="BestBuy_Negative" time="87.695" errors="0" timestamp="2024-03-21T15:57:04 IST">
  <testcase classname="com.test.BestBuy_TC02" name="login_MandPassword_TC03" time="14.093"/>
  <testcase classname="com.test.BestBuy_TC02" name="signUp_TC04" time="27.958">
    <failure type="java.lang.AssertionError" message="expected [An account with this email already exists.
Please sign in or use a different email address.] but found [Sorry, there was a problem creating your account.
Please review your info and try again.]">
      <![CDATA[java.lang.AssertionError: expected [An account with this email already exists.
Please sign in or use a different email address.] but found [Sorry, there was a problem creating your account.
Please review your info and try again.]
at com.test.BestBuy_TC02.signUp_TC04(BestBuy_TC02.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- signUp_TC04 -->
  <testcase classname="com.test.BestBuy_TC02" name="signIn_TC05" time="18.917"/>
</testsuite> <!-- BestBuy_Negative -->
